### ISSUE TITLE
Feedback after Game Jam

### ISSUE THREAD

**Issue by LeonMatthes** [GameDrivenDesign/godot-multiplayer-template#2]
First off, thanks for providing the template, it was really helpful to get started.

## sync.tscn
* Generally works well
* Should try to update the position, but if the object does not have a position (i.e. Node subclass), it should simply skip that step (
Or just do: `export (PoolStringArray) var synced_properties = ['position']`
* Note: If setget is used for an attribute, both `rset` and `sync.tscn` will call the setter, which is very useful!

## game.gd
* Add command-line argument for IP+port (default to localhost)
* Otherwise worked pretty reliably

## Structure of game.tscn
Instead of the current structure of:
* game
  * 1 (Server player)
  * 1234567 (client player)
  * my_level_object1
  * my_level_object2
I want to propose the following structure:
* game
  * camera (Camera2D)
  * level (Node, level_switch.gd)
    * level1 (level1.tscn)
    * 1 (Server player)
    * 12345 (Client player)
    * sync (sync.tscn)
  * clients
    * 1 (Node, or similar)
    * 12345 (Node, or similar)

Initial implementation of level_switch.gd
``` GdScript
extends Node

var level_path: String setget set_level_path

# Called when the node enters the scene tree for the first time.
func _ready():
	rset_config('level_path', MultiplayerAPI.RPC_MODE_REMOTESYNC)

func set_level(new_path: String):
	rset('level_path', new_path)

func set_level_path(new_path: String):
	level_path = new_path
	for child in get_children():
		# take care to not delete the sync component
		if child.name != 'sync':
			self.remove_child(child)
			child.queue_free()
		
	var new_level = load(new_path).instance()
	add_child(new_level)
```
In the initalization of game.gd, you can then just call:
``` GdScript
$level.set_level('res://level/level.tscn')
```
To load any custom level you want.

This should of course be done before auto-creating the players.

The advantage of adding the level as a subnode of the game is of course, that it can be switched really easily.
If players can die, it also makes a lot of sense to decouple player + client, so that for each connected client, a client node exists, but not necessarily a player (i.e. player is dead atm.)
This is also helpful when changing levels, as the entire level including players can just be deleted and for each node under `$clients`, a new player can be created.

For example, this is my code to switch levels in `game.gd`:
``` GdScript
func switch_level(level_path: String):
	$level.set_level(level_path)
	
	for player_id in $clients.get_children():
		spawn_new_player(player_id.id)
	register_main()
```
spawn_new_player basically boils down to:
``` GdScript
func spawn_new_player():
	var new_player = register_player(player_id, null, {})
	
        # Do some game logic to figure initialize the new player
	
	rpc("register_player", player_id, new_player.position, new_player.get_sync_state())
```

Then _ready can just be:
``` GdScript
        # ..... Create, the network peer, but do not! create any players!
        get_tree().set_network_peer(peer)
	
	if not is_client:
		if not is_dedicated:
			register_player_id(1)
		switch_level('res://level/my_level.tscn')
```

**Comment by LeonMatthes** [comment]
I've noticed that using the Level_Switch + `sync`-Component to load the initial level leads to an interesting bug.

Some objects that have a sync-Component, appear twice on client instances.
I imagine this happens for the following reason:
1. A client connects
2. The client gets sent the state for all objects that have a sync component
3. This state includes the level_switch node
4. The level-switch node loads the level, including any `synced` nodes in it
5. The `synced` nodes that are already present in the level on the server are copied to the server via spawn_object as well.
6. Because the spawn_object function unfortunately does not respect the hierarchy of nodes, it will spawn a second version of the `synced` object, flattened right under the $level node

Edit: Fixed it, by calling rpc_id(player_id, "spawn_object", $level...) first, and modifying spawn_object like this:
``` GdScript
remote func spawn_object(name: String, parent: NodePath, filename: String, position: Vector2, state: Dictionary):
	# The parent_node MUST exist before spawning the object
        var parent_node: Node = get_node(parent)
	
	# either create the object or just find the existing one
	var object: Node2D = parent_node.get_node_or_null(name)
	if not object:
		object = load(filename).instance()
		object.name = name
		$level.add_child(object)
	
	# rigid bodys need to be our syncable_rigid_body because you can't set the
	# position or any other physics property outside of its own _integrate_forces
	if object is RigidBody2D:
		object.use_update(position, state)
	else:
		object.position = position
	for property in state:
		object.set(property, state[property])
	
	return object
```

**Comment by tom95** [comment]
Good catch! Your proposal contains one mistake I believe, the `object` should be added to parent_node rather than $level. We had also encountered that shortcoming and addressed it in the same way: https://github.com/s4pu/DontDieTogether/blob/master/game/game.gd#L129

One part I'm not sure about is the behavior of this code when nested sync'ed objects occur. But this might also be something to just not support if it turns out to mess with the insertion order.

**Comment by LeonMatthes** [comment]
Oh, yeah, you're right, it should definitely be `parent_node`!
We should check if there are any ordering guarantees in the get_nodes_in_group function. As long as that returns all parent objects first, that would be fine.

I think we don't have to support syncing objects who's parents aren't synced, as that doesn't really make sense, as later `rpc`/`rset` calls won't reach these objects anyways, as their NodePath won't match.

**Comment by LeonMatthes** [comment]
I've started working on a PR that incorporates the mentioned features here: #3 

The first thing I changed was the special treatment for `position` when it comes to the initial sync.
I think that should be optional, so it is possible to sync `Node` instances, that don't have a position.
That change should be pretty uncontroversial.

What's your stance on:
* Separating clients and players (clients for client-specific information, player as the unit the client is playing. Makes it easier to just delete and respawn players)
* Adding the level_switch component, so it's easy to change levels and have that synced (downside: level isn't shown in game.tscn anymore)

**Comment by tom95** [comment]
Hey, looks great already! Yes, dropping position is definitely the right call. This created a lot more headaches than benefit.

I agree with a separation between visible player objects and the connection. It had first been in place only to simplify the logic for games with little complexity (e.g. one assumption was that we would not care about being able to restart the game, which is of course a huge limitation, but makes spawning players a no-brainer).

Concerning your proposal, I believe that it looks quite solid. One thing to consider could be to move the connection information out of the node tree and into a global singleton object instead. This would then allow you to more easily switch out the entire tree without having to be careful about not removing certain objects. It may also allow for a more flexible hierarchy, for example our game required multiple nested viewports, also on the toplevel, for post processing effects. This is definitely still possible with the setup in level_switch, but it was already in the previous system a bit of a headache.

The counter proposal might be something like this then:

* connections are stored in a global `Connections` object. `Connections` offers signals for new connections and can also receive a callback that will create a new player. This callback could then be reused both when new players connect or when a level is switched and all players need to be re-created
* A downside of this is that the `Connections` object cannot make use of `rset` and friends, since it is not addressable in the tree (might be mistaken here, not sure). However, I feel like all actual game state syncing should be taken care of within the node tree anyways.
* An open question is then the best way to persist synced state across level switches, assuming that a level switch replaces the entire tree. The usual pattern in Godot would be to have these in a global singleton, however I do not know how easy it is to address this with godot's highlevel network protocol.

**Comment by LeonMatthes** [comment]
Hm, you bring up some good points.
The main purpose of level_switch in our design was that it synced the level between all clients. How would that part work if you were to replace the entire tree?

I think to decide whether the `Connections` should be nodes or not we need to further define what their purpose is. If they are basically just a list of connected id's, you're right, they don't need to be in the NodeTree, and removing them from it makes modifying the tree easier.

However, in the game we wrote, clients could queue actions that were then executed on the player character. This queue was currently completely managed in the player character. But it might make sense to handle them in one of the `Connections` instead. (Which is why I called them `Clients` originally, for that purpose that name feels better).
But I'm not sure if that would be a good design anyways, as we weren't able to test that.

**Comment by tom95** [comment]
I would argue it's actually better to queue them in the player node, rather than in the persistent connection, as I assume when the player dies, the queue should also be emptied. Scores that are associated with players across levels, however, are definitely an example where we need to then give users of the framework a new solution. Thinking about it now, I believe putting the Connections aside from the node tree is most in line with the usual Godot patterns, as also regular Godot games would require you to store such information external to the node tree.

**Comment by LeonMatthes** [comment]
That's fair, I didn't know about that godot pattern of storing persistent data outside the tree, but that makes sense.

I can add that to the PR. Should I still add the level_switch subnode to the game.tscn?
In my opinion it is still really valuable to switch the level in a subnode, as then level loading is synced automatically between all clients, and that logic is contained in a single branch of the tree.
And any objects that might have to exist between levels (maybe a Camera, UI, etc.) could be stored outside the level as separate nodes.

**Comment by tom95** [comment]
Hm I'm a bit torn. I also really like the design of it, but I'm uncertain if we're maybe promoting a design for levels that contradicts Godot's notion of it. However, I think I would vote for including it for now and investigating the alternative later on.

**Comment by LeonMatthes** [comment]
Alright, let's try it, I'll probably update the PR this evening

**Comment by LeonMatthes** [comment]
The PR has been updated with a list of clients and a level_switch component

I've followed the naming convention:
* `client`: An object representing a user that is currently playing on the server
* `player`: A character, by default controlled by one `client`

**Comment by LeonMatthes** [comment]
I also think we should refactor the player to simply use a `sync` component instead of being a special case.

Using `setget` on the id should make it easy to change the network_master on all clients accordingly.
And we can simply set the group in _init
Then `spawn_new_player(id)` would boil down to something like:
``` GdScript
var new_player = spawn_object(id, $level.get_path(), "res://player/player.tscn", {})
new_player.id = id
rpc("spawn_object", new_player.name, new_player.get_parent().get_path(), ...)
```

And we could remove any player related code from server_client_connected as they would be synced automatically

**Comment by LeonMatthes** [comment]
I added another PR for that too, so you can decide whether you like that change (see #4 )
